In [1]:
from pathlib import Path
import json

In [2]:
from bin.rand_exp_config import generate_rand_conf
from bin.refactored_experiment import experiment_tsp
from libs.data_loading.utils import ExperimentType
from libs.data_loading.loaders import get_env_data

In [3]:
env_data = get_env_data(Path("data/environments/map_2021-12-15_08-57-55_tsp.json"))
conf = generate_rand_conf(
    ExperimentType.TSP,
    env_data,
    population_size=10,
    generation_n=100,
    timeout=60,
    early_stop_iters=50
)

before fixing: [0 4 7 8 5 1 3 6 2 0]
[0 7 3 2 4 5 1 6 8 0]
[0 3 1 6 5 2 7 4 8 0]
[0 3 1 8 6 4 5 7 2 0]
[0 8 5 4 7 6 3 1 2 0]
[0 2 8 3 4 5 1 6 7 0]
[0 4 3 8 1 5 7 6 2 0]
[0 2 7 4 1 6 8 3 5 0]
[0 2 4 7 1 8 3 6 5 0]
[0 6 2 4 5 8 3 7 1 0]
__fix_tsp chromosome = [0, 3, 1, 6, 5, 2, 7, 4, 8, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 3, 1, 6, 5, 2, 7, 4, 8, 0]
find invalid transitions solution = [0, 3, 4, 6, 5, 2, 1, 7, 8, 0]
fixed individual 2
__fix_tsp chromosome = [0, 3, 1, 8, 6, 4, 5, 7, 2, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 3, 1, 8, 6, 4, 5, 7, 2, 0]
__fix_tsp chromosome = [0, 2, 7, 5, 4, 6, 8, 1, 3, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 2, 7, 5, 4, 6, 8, 1, 3, 0]
will regenerate individual 3
__fix_tsp chromosome = [0, 8, 1, 7, 3, 4, 5, 6, 2, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 8, 1, 7, 3, 4, 5, 6, 2, 0]
find invalid transitions solution = [0, 8, 1, 

In [4]:
conf_path = Path("test_experiment_config.json")
conf.save_to_json(conf_path)

In [5]:
results_path = "test_experiment_results.json"
experiment_tsp(
    str(conf_path),
    results_path,
    population_size=10,
    generation_n=100,
    exp_timeout=60,
    early_stop_n=50,
)
with open(results_path, "r") as f:
    d = json.loads(f.read())
    print("\n".join(f"{k}: {v}" for k, v in d.items()))

exp_data_to_validate['crossover_kwargs'] = {'k': 4, 'inversion_p': 0.3}


Output()

initial: len(costs) = 10, len(population) = 10
#################################################
in while: len(costs) = 10, len(population) = 10
costs = [37.748850254513506, 38.27260666066451, 22.477165765191426, 37.748850254513506, 37.748850254513506, inf, inf, 29.1125429999232, 24.455763402057258, inf]
attractiveness = array([-37.74885025, -38.27260666, -22.47716577, -37.74885025,
       -37.74885025,         -inf,         -inf, -29.112543  ,
       -24.4557634 ,         -inf])
len(parent_costs) = 10
crossover_kwargs = {'k': 4, 'inversion_p': 0.3}
__fix_tsp chromosome = [0, 4, 2, 5, 2, 8, 7, 6, 4, 3]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 4, 2, 5, 2, 8, 7, 6, 4, 0]
find invalid transitions solution = [0, 3, 4, 5, 2, 8, 7, 1, 6, 0]
__fix_tsp chromosome = [7, 1, 6, 1, 0, 0, 3, 8, 5, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 1, 6, 1, 0, 0, 3, 8, 5, 0]
find invalid transitions solution = [0, 1, 6, 7, 2, 4, 3, 8, 5, 0]
__fix_ts

C:\Users\obszansk\my\bachelor-thesis-project\.venv\lib\site-packages\numpy\core\_methods.py:229: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


end_reason: exception
best_sol: []
experiment_config_path: test_experiment_config.json
end_iter: 28
exception: ValueError: not enough values to unpack (expected 2, got 1)
traceback:   File "C:\Users\obszansk\my\bachelor-thesis-project\bin\refactored_experiment.py", line 73, in experiment_tsp
    for i, (next_gen, next_gen_data, rng) in enumerate(stepper):

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\steppers\tsp.py", line 112, in genetic_stepper_tsp
    checked_offspring = replace_invalid_offspring(

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\population\natural_selection.py", line 141, in replace_invalid_offspring
    raise e

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\population\natural_selection.py", line 138, in replace_invalid_offspring
    p1c, p2c = parent_costs[ix : ix + 2]

