In [1]:
from pathlib import Path
import json

In [2]:
from bin.rand_exp_config import generate_rand_conf
from bin.refactored_experiment import experiment_tsp
from libs.data_loading.utils import ExperimentType
from libs.data_loading.loaders import get_env_data

In [3]:
env_data = get_env_data(Path("data/environments/map_2021-12-15_08-57-55_tsp.json"))
conf = generate_rand_conf(
    ExperimentType.TSP,
    env_data,
    population_size=10,
    generation_n=100,
    timeout=60,
    early_stop_iters=50
)

before fixing: [0 3 5 8 7 1 2 6 4 0]
[0 2 5 1 3 4 8 7 6 0]
[0 6 4 3 1 7 8 2 5 0]
[0 1 7 2 4 5 8 6 3 0]
[0 8 7 2 5 3 6 1 4 0]
[0 5 3 6 2 1 8 7 4 0]
[0 4 2 7 5 3 6 8 1 0]
[0 8 2 3 4 7 6 5 1 0]
[0 3 6 4 1 7 5 2 8 0]
[0 1 6 4 3 7 2 8 5 0]
__fix_tsp chromosome = [0, 3, 5, 8, 7, 1, 2, 6, 4, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 3, 5, 8, 7, 1, 2, 6, 4, 0]
__fix_tsp chromosome = [0, 4, 6, 2, 1, 7, 8, 5, 3, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 4, 6, 2, 1, 7, 8, 5, 3, 0]
will regenerate individual 0
__fix_tsp chromosome = [0, 2, 3, 4, 7, 1, 5, 8, 6, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 2, 3, 4, 7, 1, 5, 8, 6, 0]
find invalid transitions solution = [0, 2, 3, 4, 7, 1, 5, 8, 6, 0]
fixed individual 0
__fix_tsp chromosome = [0, 2, 5, 1, 3, 4, 8, 7, 6, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 2, 5, 1, 3, 4, 8, 7, 6, 0]
__fix_tsp chromosome = [0, 6, 7, 8, 4, 3, 1, 5

In [4]:
conf_path = Path("test_experiment_config.json")
conf.save_to_json(conf_path)

In [5]:
results_path = "test_experiment_results.json"
experiment_tsp(
    str(conf_path),
    results_path,
    population_size=10,
    generation_n=100,
    exp_timeout=60,
    early_stop_n=50,
)
with open(results_path, "r") as f:
    d = json.loads(f.read())
    print("\n".join(f"{k}: {v}" for k, v in d.items()))

exp_data_to_validate['crossover_kwargs'] = {'lam': 2, 'inversion_p': 0.2}


Output()

initial: len(costs) = 10, len(population) = 10
in while: len(costs) = 10, len(population) = 10
costs = [28.313403722349392, 33.113423764186614, inf, 22.037197821590954, 28.67338130509688, 42.78989974140286, inf, 24.306203678696424, 44.25967542303572, 43.65006904983824]
attractiveness = array([-28.31340372, -33.11342376,         -inf, -22.03719782,
       -28.67338131, -42.78989974,         -inf, -24.30620368,
       -44.25967542, -43.65006905])
len(parent_costs) = 10
crossover_kwargs = {'lam': 2, 'inversion_p': 0.2}
__fix_tsp chromosome = [0, 7, 6, 4, 3, 8, 5, 2, 2, 0]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 7, 6, 4, 3, 8, 5, 2, 2, 0]
find invalid transitions solution = [0, 7, 1, 4, 3, 8, 5, 2, 6, 0]
__fix_tsp chromosome = [3, 0, 5, 1, 1, 7, 6, 4, 0, 8]
initial_vx = 0(<class 'int'>)
find invalid transitions solution = [0, 0, 5, 1, 1, 7, 6, 4, 0, 0]
find invalid transitions solution = [0, 3, 5, 8, 6, 7, 1, 4, 2, 0]
__fix_tsp chromosome = [0, 7, 3, 2, 4, 5, 

C:\Users\obszansk\my\bachelor-thesis-project\.venv\lib\site-packages\numpy\core\_methods.py:229: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


end_reason: exception
best_sol: []
experiment_config_path: test_experiment_config.json
end_iter: 0
exception: ValueError: a and p must have same size
traceback:   File "C:\Users\obszansk\my\bachelor-thesis-project\bin\refactored_experiment.py", line 71, in experiment_tsp
    for i, (next_gen, next_gen_data, rng) in enumerate(take(generation_n, stepper)):

  File "C:\Users\obszansk\my\bachelor-thesis-project\.venv\lib\site-packages\more_itertools\recipes.py", line 73, in take
    return list(islice(iterable, n))

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\steppers\tsp.py", line 85, in genetic_stepper_tsp
    parents, parent_costs, rng = select_best_parents_with_probability(

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\population\parent_selectors.py", line 110, in select_best_parents_with_probability
    raise e

  File "C:\Users\obszansk\my\bachelor-thesis-project\libs\optimizers\algorithms\genetic\