In [20]:
import numpy as np
import itertools as it
import more_itertools as mit

In [4]:
m = np.random.randint(0, 100, size=(5, 5))
m

array([[15, 65, 40, 12, 56],
       [97, 38, 65,  2, 83],
       [46, 72, 63, 76, 35],
       [39, 81, 88,  1, 66],
       [26, 54, 40, 81, 66]])

In [7]:
m[1, 2]

65

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
list(zip(*[(1, 2), (3, 4)]))

In [19]:
list(itt.permutations([True, False], 2))

[(True, False), (False, True)]

In [23]:
m = np.array(list(mit.chunked(range(16), 4)))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.triu(m, 1)

array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0,  0, 11],
       [ 0,  0,  0,  0]])

In [31]:
np.diag([True, True, True])

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])